/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;
import java.beans.Statement;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ListaPublicacion;
import static vista.Inicio.fondo;
import static vista.Inicio.fondo1;

/**
 *
 * @author asus
 */
public class Info_consul_eliminar extends javax.swing.JPanel {

    private ListaPublicacion modelo;
    DefaultTableModel tabla;
    private String titu[] = {"ISBN", "TITULO", "AUTOR", "TIPO", "ANIO", "COSTO", "No PAG", "EDICION", "FORMATO", "DURACION", "PESO"};
    private String datos[][] = {null};
    
    public Info_consul_eliminar() {
        initComponents();
        
        this.modelo = new ListaPublicacion();
        tabla = new DefaultTableModel();
        for (int i=0; i<titu.length; i++)
        {
            tabla.addColumn(titu[i]);
        }
        tabla1.setModel(tabla);
        
    }
    
    public void datosText() {
        BufferedReader bufferedReader = null;

        try {
            
            bufferedReader = new BufferedReader(new FileReader("datos.txt"));
            String line = bufferedReader.readLine();

            while (line != null) {
                String[] rowfields = line.split(";");
                tabla.addRow(rowfields);
                line = bufferedReader.readLine();
            }

        } catch (IOException x) {
            JOptionPane.showMessageDialog(null, "error");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        eliminar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Consultar");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 140, 60));

        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 340, -1));

        eliminar.setBackground(new java.awt.Color(0, 0, 0));
        eliminar.setText("ELIMINAR");
        eliminar.setBorder(null);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 80, 30));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setText("<--");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        tabla1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tabla1 = new javax.swing.JTable()
        {
            public boolean isCellEditable (int rowIndex, int colIndex)
            return false;
        }
        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Isbn", "Titulo", "Autor", "Tipo", "Costo", "N. paginas", "N. edicion", "Peso", "Formato", "Duracion"
            }
        ));
        tabla1.setName("idbn,titulo,autor,año pub,costo,n°paginas,n°edicion,formato,peso,duracion"); // NOI18N
        tabla1.setRowHeight(22);
        jScrollPane1.setViewportView(tabla1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 737, 250));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Digite el Isbn:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 100, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        String dato = buscar.getText();
        
        for (int i=0; i<tabla1.getRowCount(); i++)
        {
            if (tabla1.getValueAt(i, 0).equals(dato))
            {
                tabla1.changeSelection(i, 0, false, false);
            }
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
     Inicio.fondo.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        int fila = tabla1.getSelectedRow();
        tabla.removeRow(fila);
    }//GEN-LAST:event_eliminarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscar;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla1;
    // End of variables declaration//GEN-END:variables
}
