/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author asus
 */
public class Inicio extends javax.swing.JFrame{
    registrolb panel1;
    Info_consul_eliminar panel2;
    /**
     * Creates new form Libreria
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        panel1 = new registrolb();
        panel2 = new Info_consul_eliminar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        ingrelb = new javax.swing.JToggleButton();
        consultarlb = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fondo1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setForeground(new java.awt.Color(153, 153, 153));
        fondo.setToolTipText("nb ");
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(0, 51, 51));
        jTextField1.setFont(new java.awt.Font("Modern No. 20", 0, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 255, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        fondo.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, 92));

        ingrelb.setBackground(new java.awt.Color(255, 255, 255));
        ingrelb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ingrelb.setText("Ingresar libro");
        ingrelb.setBorder(null);
        ingrelb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingrelbMouseClicked(evt);
            }
        });
        ingrelb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingrelbActionPerformed(evt);
            }
        });
        fondo.add(ingrelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 158, 54));

        consultarlb.setBackground(new java.awt.Color(255, 255, 255));
        consultarlb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        consultarlb.setText("Consultar libro");
        consultarlb.setBorder(null);
        consultarlb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarlbActionPerformed(evt);
            }
        });
        fondo.add(consultarlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 158, 57));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setText("Gestion de libros ");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 340, 70));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("x");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        fondo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 40, 20));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        fondo1.setBackground(new java.awt.Color(255, 255, 255));
        fondo1.setToolTipText("nb ");
        fondo1.setPreferredSize(new java.awt.Dimension(530, 510));

        javax.swing.GroupLayout fondo1Layout = new javax.swing.GroupLayout(fondo1);
        fondo1.setLayout(fondo1Layout);
        fondo1Layout.setHorizontalGroup(
            fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        fondo1Layout.setVerticalGroup(
            fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ingrelbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingrelbActionPerformed
      fondo1.setVisible(true);
      fondo.setVisible(false);
      
      panel1.setSize(810, 583);
      panel1.setLocation(0, 0);
      
      fondo1.removeAll();
      fondo1.add(panel1, BorderLayout.CENTER);
      fondo1.revalidate();
      fondo1.repaint();
    }//GEN-LAST:event_ingrelbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void consultarlbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarlbActionPerformed
      panel2.datosText();
        fondo1.setVisible(true);
      fondo.setVisible(false);
      
      panel2.setSize(810, 583);
      panel2.setLocation(0, 0);
      
      fondo1.removeAll();
      fondo1.add(panel2, BorderLayout.CENTER);
      fondo1.revalidate();
      fondo1.repaint();
    }//GEN-LAST:event_consultarlbActionPerformed

    private void ingrelbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrelbMouseClicked
        
    }//GEN-LAST:event_ingrelbMouseClicked
     public void run() {
                new Inicio().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton consultarlb;
    public static javax.swing.JPanel fondo;
    public static javax.swing.JPanel fondo1;
    private javax.swing.JToggleButton ingrelb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}