/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.AudioLibro;
import modelo.Libro;
import modelo.ListaPublicacion;
import modelo.Publicacion;
import static vista.registrolb.modelo;

/**
 *
 * @author asus
 */
public class registrolb extends javax.swing.JPanel {
    
    public static ListaPublicacion modelo;
    public static Publicacion publicacion;
    FileWriter salvar;
    

    public void registrarPublicacion() {
        Publicacion nuevaPublicacion = this.leerNuevaPublicacion();
        this.modelo.insertarPublicacion(nuevaPublicacion);
    }
    
    public Publicacion leerNuevaPublicacion() {
        
        boolean salir=true;
        
        while(salir == true)
        {
            try
            {
                String isbn = istisbn.getText();
                String titulo = isttitulo.getText();
                String autor = istautor.getText();
                int anio = Integer.parseInt(istañopublic.getText());
                double costo = Double.parseDouble(istcosto.getText());
                int tipo = selectipolibro.getSelectedIndex();

                if (tipo == 1) {
                    int nPag = Integer.parseInt(textnpajinas1.getText());
                    int edicion = Integer.parseInt(textnedicion1.getText());

                    publicacion = new Libro(nPag, edicion, isbn, titulo, autor, anio, costo);
                }
                if (tipo == 2) {

                    int nPag = 0;
                    int edicion = 0;
                    String formato = textformat.getText();
                    double duracion = Double.parseDouble(textduracion.getText());
                    double peso = Double.parseDouble(textpeso.getText());
                    publicacion = new AudioLibro(isbn,titulo,autor,anio,costo,duracion,peso,formato);
                    
                    if (tipo == 0) 
                    {
                        JOptionPane.showMessageDialog(null, "ingrese el tipo");
                    }
                }
                
                salir = false;
            }catch(java.lang.NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null, "llene todos los campos");
                salir = true;
                istisbn.setText("");
                isttitulo.setText("");
                istautor.setText("");
                istañopublic.setText("");
                istcosto.setText("");
                selectipolibro.setSelectedIndex(0);
                textnpajinas1.setText("");
                textnedicion1.setText("");
                textformat.setText("");
                textduracion.setText("");
                textpeso.setText("");
            }
        }
        
        return publicacion;
    }

    public void textPublicaciones() {

        try {
            salvar = new FileWriter("datos.txt");
            List<Publicacion> lista = this.modelo.leerPublicaciones();
            for (Publicacion p : lista) {
                salvar.write(p.getDataStringFormat());
            }

            salvar.close();
        } catch (IOException x) {
            JOptionPane.showMessageDialog(null, "error");
        }

    } 
    
    /**
     * Creates new form NewJPanel
     */
    public registrolb() {
        
        initComponents();
        panelaudiolibro.setVisible(false);
        this.modelo = new ListaPublicacion();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ATRAS = new javax.swing.JButton();
        selectipolibro = new javax.swing.JComboBox<>();
        GUARDAR = new javax.swing.JButton();
        istisbn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        isttitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        istautor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        istañopublic = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        istcosto = new javax.swing.JTextField();
        limpiar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        panellibro = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        textnpajinas1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textnedicion1 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        panelaudiolibro = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        textformat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textduracion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        textpeso = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ATRAS.setBackground(new java.awt.Color(255, 255, 255));
        ATRAS.setText("<--");
        ATRAS.setBorder(null);
        ATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATRASActionPerformed(evt);
            }
        });
        jPanel1.add(ATRAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        selectipolibro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        selectipolibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo de libro", "libro", "audio libro" }));
        selectipolibro.setToolTipText("");
        selectipolibro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        selectipolibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectipolibroActionPerformed(evt);
            }
        });
        jPanel1.add(selectipolibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        GUARDAR.setBackground(new java.awt.Color(255, 255, 255));
        GUARDAR.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        GUARDAR.setText("Guardar");
        GUARDAR.setBorder(null);
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });
        jPanel1.add(GUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, 80, 30));

        istisbn.setBorder(null);
        istisbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                istisbnActionPerformed(evt);
            }
        });
        jPanel1.add(istisbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 140, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Isbn:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 40, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel2.setText("Insertar publicaciones");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 440, 70));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Titulo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 59, -1));

        isttitulo.setBorder(null);
        isttitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isttituloActionPerformed(evt);
            }
        });
        jPanel1.add(isttitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 140, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Autor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        istautor.setBorder(null);
        istautor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                istautorActionPerformed(evt);
            }
        });
        jPanel1.add(istautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 140, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Año de publicación:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        istañopublic.setBorder(null);
        istañopublic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                istañopublicActionPerformed(evt);
            }
        });
        istañopublic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                istañopublicKeyTyped(evt);
            }
        });
        jPanel1.add(istañopublic, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 120, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Costo: $");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        istcosto.setBorder(null);
        jPanel1.add(istcosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 140, 30));

        limpiar.setBackground(new java.awt.Color(255, 255, 255));
        limpiar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        limpiar.setText("Limpiar casillas");
        limpiar.setBorder(null);
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, 120, 40));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 140, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 140, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 140, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 140, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 120, -1));

        panellibro.setBackground(new java.awt.Color(255, 255, 255));
        panellibro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("N. paginas:");
        panellibro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        textnpajinas1.setBorder(null);
        textnpajinas1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textnpajinas1KeyTyped(evt);
            }
        });
        panellibro.add(textnpajinas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 103, 20));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("N. edición:");
        panellibro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        textnedicion1.setBorder(null);
        textnedicion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnedicion1ActionPerformed(evt);
            }
        });
        textnedicion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textnedicion1KeyTyped(evt);
            }
        });
        panellibro.add(textnedicion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 103, 20));
        panellibro.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 0));
        panellibro.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 82, 110, 0));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        panellibro.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 100, -1));

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        panellibro.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 100, -1));

        jPanel1.add(panellibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 420, 110));

        panelaudiolibro.setBackground(new java.awt.Color(255, 255, 255));
        panelaudiolibro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("FORMATO");
        panelaudiolibro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        textformat.setBorder(null);
        panelaudiolibro.add(textformat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 103, 20));

        jLabel9.setText("DURACION");
        panelaudiolibro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        textduracion.setBorder(null);
        panelaudiolibro.add(textduracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 103, 20));

        jLabel12.setText("PESO");
        panelaudiolibro.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        textpeso.setBorder(null);
        textpeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textpesoActionPerformed(evt);
            }
        });
        panelaudiolibro.add(textpeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 110, 20));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        panelaudiolibro.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 100, -1));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        panelaudiolibro.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 100, 10));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        panelaudiolibro.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 110, 20));

        jPanel1.add(panelaudiolibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 420, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATRASActionPerformed
        Inicio.fondo.setVisible(true);
    }//GEN-LAST:event_ATRASActionPerformed

    private void selectipolibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectipolibroActionPerformed

        if(selectipolibro.getSelectedItem().equals("audio libro"))
        {
            panellibro.setVisible(false);
            panelaudiolibro.setVisible(true);
        }
        if(selectipolibro.getSelectedItem().equals("libro"))
        {
            panellibro.setVisible(true);
            panelaudiolibro.setVisible(false);
        }
    }//GEN-LAST:event_selectipolibroActionPerformed

    private void istisbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_istisbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_istisbnActionPerformed

    private void isttituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isttituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isttituloActionPerformed

    private void istañopublicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_istañopublicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_istañopublicActionPerformed

    private void istautorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_istautorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_istautorActionPerformed

    private void textpesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textpesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textpesoActionPerformed

    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARActionPerformed
        leerNuevaPublicacion();
        registrarPublicacion();
        textPublicaciones();
    }//GEN-LAST:event_GUARDARActionPerformed

    private void istañopublicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_istañopublicKeyTyped
        char validar = evt.getKeyChar();
        
        if (Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "solo numeros en año pub.");
        }
    }//GEN-LAST:event_istañopublicKeyTyped

    private void textnpajinas1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textnpajinas1KeyTyped
        char validar = evt.getKeyChar();
        
        if (Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "solo numeros en n° pajinas");
        }
    }//GEN-LAST:event_textnpajinas1KeyTyped

    private void textnedicion1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textnedicion1KeyTyped
        char validar = evt.getKeyChar();
        
        if (Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "solo numeros en num edic.");
    }//GEN-LAST:event_textnedicion1KeyTyped
    }
    
    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        istisbn.setText("");
        isttitulo.setText("");
        istautor.setText("");
        istañopublic.setText("");
        istcosto.setText("");
        selectipolibro.setSelectedIndex(0);
        textnpajinas1.setText("");
        textnedicion1.setText("");
        textformat.setText("");
        textduracion.setText("");
        textpeso.setText("");
    }//GEN-LAST:event_limpiarActionPerformed

    private void textnedicion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnedicion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textnedicion1ActionPerformed

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATRAS;
    private javax.swing.JButton GUARDAR;
    private javax.swing.JTextField istautor;
    private javax.swing.JTextField istañopublic;
    private javax.swing.JTextField istcosto;
    private javax.swing.JTextField istisbn;
    private javax.swing.JTextField isttitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton limpiar;
    private javax.swing.JPanel panelaudiolibro;
    public static javax.swing.JPanel panellibro;
    private javax.swing.JComboBox<String> selectipolibro;
    private javax.swing.JTextField textduracion;
    private javax.swing.JTextField textformat;
    private javax.swing.JTextField textnedicion1;
    private javax.swing.JTextField textnpajinas1;
    private javax.swing.JTextField textpeso;
    // End of variables declaration//GEN-END:variables
}
